//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirDummy
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactionTable
    {
        public string IDENTIFIER_ROOT { get; set; }
        public string IDENTIFIER_AFFECTED { get; set; }
        public string ACCOUNT_ROOT { get; set; }
        public string ACCOUNT_AFFECTED { get; set; }
        public string TYPE { get; set; }
        public System.DateTime TRANSDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal BALANCE { get; set; }
    }
}
